/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.loadTable;
import Model.Diem;
import java.sql.*;
import javax.swing.*;
import Controller.ConnectDAL;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.HashSet;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;

    public class jfmDiem extends javax.swing.JFrame {

        public static String sql ="SELECT d.MaSV, d.MaMH, d.DiemCC, d.DiemTX, d.DiemGK, d.DiemThi, (d.DiemCC + d.DiemTX + d.DiemGK * 3 + d.DiemThi * 5) / 10 AS DiemTongKet " +
                              "FROM DIEM d " +
                              "INNER JOIN lopHoc l ON d.MaSV = l.MaSV AND d.MaMH = l.MaMH";

        public static Connection conn = ConnectDAL.getConnect();
        public static String diem;
        public static String diem1;

        public jfmDiem() {
        initComponents();
        loadTable.loadData(sql, jtbDiem);
        loadDiem();
        loadcbMaSV();
        // Đóng cứng trường văn bản jtxtTenSV và jtxtTenMH
        jtxtTenSV.setEditable(false);
        jtxtTenMH.setEditable(false);
    }

    public void loadDiem() {
    loadTable.loadData(sql, jtbDiem);
    
    HashSet<String> uniqueStudents = new HashSet<>();
    for (int i = 0; i < jtbDiem.getRowCount(); i++) {
        String maSV = jtbDiem.getValueAt(i, 0).toString(); // Assuming MaSV is in the first column
        uniqueStudents.add(maSV);
    }
    
    this.lblTongDiem.setText("Tổng số sinh viên có điểm: " + uniqueStudents.size());
}
        
    public void loadcbMaSV() {
    String sql = "select distinct MaSV from lopHoc";
    try {
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        while (rs.next()) {
            this.cbMaSV.addItem(rs.getString("MaSV"));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e, "Thông Báo Lỗi", JOptionPane.ERROR_MESSAGE);
    }
}

    public void loadcbMaMH(String maSV) {
    String sql = "select distinct MaMH from lopHoc where MaSV = ?";
    try {
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, maSV);
        ResultSet rs = pst.executeQuery();
        while (rs.next()) {
            this.cbMaMH.addItem(rs.getString("MaMH"));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e, "Thông Báo Lỗi", JOptionPane.ERROR_MESSAGE);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbMaSV = new javax.swing.JComboBox<>();
        cbMaMH = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDiemCC = new javax.swing.JTextField();
        txtDiemTX = new javax.swing.JTextField();
        txtDiemThi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDiemGK = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDiem = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        lblTongDiem = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtTenMH = new javax.swing.JTextField();
        jtxtTenSV = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Điểm Sinh Viên");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Mã Sinh Viên:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Mã Môn Học:");

        cbMaSV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbMaSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaSVActionPerformed(evt);
            }
        });

        cbMaMH.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbMaMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaMHActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Điểm CC:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Điểm TX:");

        txtDiemCC.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtDiemCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemCCActionPerformed(evt);
            }
        });

        txtDiemTX.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtDiemTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemTXActionPerformed(evt);
            }
        });

        txtDiemThi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtDiemThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemThiActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Điểm GK:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Điểm Thi:");

        txtDiemGK.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtDiemGK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemGKActionPerformed(evt);
            }
        });

        jtbDiem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtbDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbDiem.setRowHeight(22);
        jtbDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbDiem);

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/remove.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update (2).png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        lblTongDiem.setText("Tổng số sinh viên có điểm:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Tên Môn Học:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Tên Sinh Viên:");

        jtxtTenMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTenMHActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton1.setText("Xuất PDF");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(280, 280, 280)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel2)
                                .addGap(13, 13, 13)
                                .addComponent(cbMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel9)
                                .addGap(38, 38, 38)
                                .addComponent(jtxtTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3)
                                .addGap(16, 16, 16)
                                .addComponent(cbMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel8)
                                .addGap(41, 41, 41)
                                .addComponent(jtxtTenMH, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4)
                                .addGap(44, 44, 44)
                                .addComponent(txtDiemCC, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(jLabel6)
                                .addGap(73, 73, 73)
                                .addComponent(txtDiemGK, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel5)
                                .addGap(44, 44, 44)
                                .addComponent(txtDiemTX, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(jLabel7)
                                .addGap(71, 71, 71)
                                .addComponent(txtDiemThi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTongDiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cbMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jtxtTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cbMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jtxtTenMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtDiemCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtDiemGK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtDiemTX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtDiemThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblTongDiem)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDiemMouseClicked
        try
        {
            int row = this.jtbDiem.getSelectedRow(); // lấy dòng tại con trỏ chuột
            String IDrow = (this.jtbDiem.getModel().getValueAt(row, 0)).toString(); // Lấy giá trị tại con trỏ chuột theo kiểu string
            String IDrow1 = (this.jtbDiem.getModel().getValueAt(row, 1)).toString();
            String sql1 = "select * from DIEM where MaSV='"+IDrow+"' and MaMH='"+IDrow1+"'";
            ResultSet rs = loadTable.showTextField(sql1);
            // đọc dữ liệu tại dòng "IDrow"
            if(rs.next()) // nếu có dữ liệu
            {
                diem= rs.getString("MaSV");
                diem1= rs.getString("MaMH");
                this.cbMaSV.setSelectedItem(rs.getString("MaSV"));
                this.cbMaMH.setSelectedItem(rs.getString("MaMH"));
                this.txtDiemCC.setText(rs.getString("DiemCC"));
                this.txtDiemTX.setText(rs.getString("DiemTX"));
                this.txtDiemGK.setText(rs.getString("DiemGK"));
                this.txtDiemThi.setText(rs.getString("DiemThi"));
                
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }                                       

    }//GEN-LAST:event_jtbDiemMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
        // Kiểm tra các trường điểm có rỗng hay không
        if (this.txtDiemCC.getText().length() == 0 || this.txtDiemTX.getText().length() == 0 || 
            this.txtDiemGK.getText().length() == 0 || this.txtDiemThi.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        } else {
            // Lấy giá trị từ các trường điểm
            double diemCC = Double.parseDouble(this.txtDiemCC.getText());
            double diemTX = Double.parseDouble(this.txtDiemTX.getText());
            double diemGK = Double.parseDouble(this.txtDiemGK.getText());
            double diemThi = Double.parseDouble(this.txtDiemThi.getText());

            // Kiểm tra giá trị điểm có nằm trong khoảng từ 0 đến 10 hay không
            if (diemCC < 0 || diemCC > 10 || diemTX < 0 || diemTX > 10 || 
                diemGK < 0 || diemGK > 10 || diemThi < 0 || diemThi > 10) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập điểm trong khoảng từ 0 đến 10", "Thông Báo", JOptionPane.ERROR_MESSAGE);
            } else {
                // Nếu tất cả các điểm đều hợp lệ, thêm điểm cho sinh viên
                Diem.themDiemSV(this.cbMaSV.getSelectedItem().toString(), this.cbMaMH.getSelectedItem().toString(), 
                                this.txtDiemCC.getText(), this.txtDiemTX.getText(), this.txtDiemGK.getText(), this.txtDiemThi.getText());
                loadDiem();
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Vui lòng nhập giá trị điểm hợp lệ", "Thông Báo", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if( this.txtDiemCC.getText().length()==0 || this.txtDiemTX.getText().length()==0 || this.txtDiemGK.getText().length()==0 || this.txtDiemThi.getText().length()==0 )
           JOptionPane.showMessageDialog(null,"Vui lòng nhập đầy đủ thông tin","Thông Báo",1);
        else
       {
           Diem.suaDiemSV(diem,diem1,this.cbMaSV.getSelectedItem().toString(), this.cbMaMH.getSelectedItem().toString(),this.txtDiemCC.getText(), this.txtDiemTX.getText(), this.txtDiemGK.getText(),this.txtDiemThi.getText());
             loadDiem();
       }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if(JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa điểm sinh viên có mã ''"+diem+"'' không?","Thông Báo",2)==0)
            {
                Diem.xoaDiemSV(diem,diem1);
            }
            loadDiem();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void cbMaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaSVActionPerformed
        if (cbMaSV.getSelectedItem() != null) {
        String maSV = cbMaSV.getSelectedItem().toString();
        cbMaMH.removeAllItems();  // Xóa các mục cũ trong cbMaMH
        loadcbMaMH(maSV);
        String tenSV = getTenSV(maSV);
        jtxtTenSV.setText(tenSV);
    }
    }//GEN-LAST:event_cbMaSVActionPerformed

    private void cbMaMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaMHActionPerformed
        if (cbMaMH.getSelectedItem() != null) {
        String maMH = cbMaMH.getSelectedItem().toString();
        String tenMH = getTenMH(maMH);
        jtxtTenMH.setText(tenMH);
    }
    }//GEN-LAST:event_cbMaMHActionPerformed

    private void jtxtTenMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTenMHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTenMHActionPerformed

    private void txtDiemCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemCCActionPerformed
        
    }//GEN-LAST:event_txtDiemCCActionPerformed

    private void txtDiemGKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemGKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemGKActionPerformed

    private void txtDiemTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemTXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemTXActionPerformed

    private void txtDiemThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemThiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemThiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Danh sách điểm sinh viên");
        MessageFormat footer = new MessageFormat("{0,number,integer}");
        try {
            PrintRequestAttributeSet set = new HashPrintRequestAttributeSet();
         set.add(OrientationRequested.LANDSCAPE);
         jtbDiem.print(JTable.PrintMode.FIT_WIDTH,header,footer,true,set,true);
         JOptionPane.showMessageDialog(null, "In thành công");
         
         
        } catch (HeadlessException | PrinterException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "In không thành công");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private String getTenSV(String maSV) {
        String tenSV = "";
        String sql = "SELECT TenSV FROM SINHVIEN WHERE MaSV = ?";
        try {
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, maSV);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                tenSV = rs.getString("TenSV");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Thông Báo Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        return tenSV;
    }
    private String getTenMH(String maMH) {
        String tenMH = "";
        String sql = "SELECT TenMH FROM MONHOC WHERE MaMH = ?";
        try {
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, maMH);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                tenMH = rs.getString("TenMH");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Thông Báo Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        return tenMH;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfmDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfmDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfmDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfmDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jfmDiem diem = new jfmDiem();
                diem.setLocationRelativeTo(null);
                diem.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbMaMH;
    private javax.swing.JComboBox<String> cbMaSV;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jtbDiem;
    private javax.swing.JTextField jtxtTenMH;
    private javax.swing.JTextField jtxtTenSV;
    private javax.swing.JLabel lblTongDiem;
    private javax.swing.JTextField txtDiemCC;
    private javax.swing.JTextField txtDiemGK;
    private javax.swing.JTextField txtDiemTX;
    private javax.swing.JTextField txtDiemThi;
    // End of variables declaration//GEN-END:variables
}
