/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.*;
import Controller.ConnectDAL;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
public class jfmTimKiemMaSV extends javax.swing.JFrame {

//    public static String sql ="Select sv.MaSV, HoSV,TenSV, NgaySinh, GioiTinh, Nhom, Diachi, SoDT, Email, Facebook, DoanVien, SoCMND, DanToc From  SINHVIEN sv  join THONGTINSV tt on sv.MaSV=tt.MaSV ";
    public jfmTimKiemMaSV() {
        initComponents();
//        loadTable.loadData(sql, jtbTK);
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTK = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTK.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnTK.setText("Tìm Kiếm");
        btnTK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Tra cứu thông tin sinh viên");

        txtTK.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTK.setForeground(new java.awt.Color(153, 153, 153));
        txtTK.setText("Nhập vào mã sinh viên");
        txtTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTKMouseClicked(evt);
            }
        });

        jtbTK.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtbTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã SV", "Họ SV", "Tên SV", "Ngày Sinh", "Giới tính", "Email"
            }
        ));
        jtbTK.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jtbTK.setRowHeight(23);
        jScrollPane1.setViewportView(jtbTK);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Nhập mã sinh viên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTK, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(280, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTK)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(btnTK, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTKMouseClicked
        txtTK.setText("");
    }//GEN-LAST:event_txtTKMouseClicked

    private void btnTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKActionPerformed
       if(txtTK.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Vui lòng nhập mã sinh viên cần tìm", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
    } else {
        String maSV = txtTK.getText();
        String sql = "SELECT * FROM SINHVIEN WHERE MaSV=?";
        
        try (Connection connection = ConnectDAL.getConnect();
             PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, maSV);
            ResultSet rs = statement.executeQuery();
            DefaultTableModel model = new DefaultTableModel();
            // Kiểm tra xem có bản ghi nào được tìm thấy không
            if (rs.next()) {
                // Nếu có, tạo một DefaultTableModel và tải dữ liệu từ ResultSet vào
                
                model.addColumn("Mã SV");
                model.addColumn("Họ");
                model.addColumn("Tên");
                model.addColumn("Ngày Sinh");
                model.addColumn("Giới tính");
                model.addColumn("Email");
                // Thêm các cột khác tùy thuộc vào cấu trúc của bảng SINHVIEN

                // Thêm dữ liệu từ ResultSet vào model
                do {
                    Object[] rowData = {
                        rs.getString("MaSV"),
                        rs.getString("HoSV"),
                        rs.getString("TenSV"),
                        rs.getString("NgaySinh"),
                        rs.getString("GioiTinh"),
                        rs.getString("Email")
                        // Thêm dữ liệu từ các cột khác của bảng
                    };
                    model.addRow(rowData);
                } while (rs.next());
                // Đặt model vào JTable
                jtbTK.setModel(model);
            } else {
                
                JOptionPane.showMessageDialog(null, "Không tìm thấy sinh viên có mã " + maSV, "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
}
                // Nếu không, hiển thị thông báo
               
        } catch (SQLException ex) {
            ex.printStackTrace();
            // Xử lý các lỗi kết nối hoặc truy vấn
        }
    }
    }//GEN-LAST:event_btnTKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfmTimKiemMaSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfmTimKiemMaSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfmTimKiemMaSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfmTimKiemMaSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfmTimKiemMaSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbTK;
    private javax.swing.JTextField txtTK;
    // End of variables declaration//GEN-END:variables
    private void setIconImage() {
    
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/iconMain.jpg")));
   
}
}
