/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.title.TextTitle;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author NHAN
 */
public class jfmThongKe extends javax.swing.JFrame {
    

    /**
     * Creates new form jfmThongKe
     */
    public jfmThongKe() {
        initComponents();
        initUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thống kê Sinh VIên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfmThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfmThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfmThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfmThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfmThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
   private void initUI(){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
            String userName = "sa";
            String password = "123456789";
            String url = "jdbc:sqlserver://localhost:1433;databaseName=QLSV1C";
            try {
            Connection conn = DriverManager.getConnection(url, userName, password);
            Statement stmt = conn.createStatement();

            String sql = "SELECT m.TenMH, COUNT(l.maSV) AS SoLuongSinhVien " +
                         "FROM lopHoc l " +
                         "INNER JOIN MONHOC m ON l.maMH = m.MaMH " +
                         "GROUP BY m.TenMH";

            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                String tenMH = rs.getString("TenMH");
                int soLuongSinhVien = rs.getInt("SoLuongSinhVien");
                dataset.addValue(soLuongSinhVien, "Số lượng sinh viên", tenMH);
            }

            rs.close();
            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        JFreeChart barChart = ChartFactory.createBarChart(
                "Số lượng sinh viên đăng ký môn học",
                "Môn học",
                "Số lượng sinh viên",
                dataset,
                PlotOrientation.VERTICAL,
                false, true, false
        );
        barChart.setTitle(new TextTitle("Số lượng sinh viên đăng ký môn học", new Font("Tohama", Font.BOLD, 18)));
        CategoryPlot plot = barChart.getCategoryPlot();

        // Tùy chỉnh phông chữ cho trục x
        plot.getDomainAxis().setLabelFont(new Font("Tohama", Font.BOLD, 14));
        plot.getDomainAxis().setTickLabelFont(new Font("Tohama", Font.PLAIN, 12));

        // Tùy chỉnh phông chữ cho trục y
        plot.getRangeAxis().setLabelFont(new Font("Tohama", Font.BOLD, 14));
        plot.getRangeAxis().setTickLabelFont(new Font("Tohama", Font.PLAIN, 12));

        // Tùy chỉnh phông chữ cho các giá trị trên biểu đồ
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setBaseItemLabelFont(new Font("Tohama", Font.PLAIN, 12));
        renderer.setBaseItemLabelsVisible(true);
        ChartPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setPreferredSize(new Dimension(800, 600));
        setContentPane(chartPanel);
       
   }
}
