/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.loadTable;
import javax.swing.*;
import Controller.ConnectDAL;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class jfmTimKiemDiem extends javax.swing.JFrame {

   public static String sql ="Select d.MaSV,sv.HoSV+' '+sv.TenSV \"HoTenSV\", d.MaMH, mh.TenMH, DiemCC, DiemTX, DiemGK,DiemTHi, ( DiemCC + DiemTX + DiemGK*3 + DiemThi*5 )/10 as DiemTongKet  From  DIEM d  join MONHOC mh on d.MaMH=mh.MaMH join SINHVIEN sv on d.MaSV= sv.MaSV";
    public jfmTimKiemDiem() {
        initComponents();
//        loadTable.loadData(sql, jtbTK);
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        btnTK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTK = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Tra Cứu Điểm Sinh Viên");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Mã Sinh Viên:");

        txtMaSV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtMaSV.setForeground(new java.awt.Color(153, 153, 153));
        txtMaSV.setText("Nhập vào mã sinh viên");
        txtMaSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMaSVMouseClicked(evt);
            }
        });

        btnTK.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnTK.setText("Tìm Kiếm");
        btnTK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKActionPerformed(evt);
            }
        });

        jtbTK.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtbTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbTK.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jtbTK.setRowHeight(23);
        jScrollPane1.setViewportView(jtbTK);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)
                        .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnTK, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel1)))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnTK, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKActionPerformed
        if(txtMaSV.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Vui lòng nhập mã sinh viên cần tìm", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
    } else {
        String sql = "Select d.MaSV, sv.HoSV+' '+sv.TenSV AS HoTenSV, d.MaMH, mh.TenMH, DiemCC, DiemTX, DiemGK, DiemTHi, (DiemCC + DiemTX + DiemGK*3 + DiemThi*5)/10 AS DiemTongKet FROM DIEM d JOIN MONHOC mh ON d.MaMH=mh.MaMH JOIN SINHVIEN sv ON d.MaSV=sv.MaSV WHERE sv.MaSV LIKE '%" + txtMaSV.getText() + "%'";
        
        try (Connection connection = ConnectDAL.getConnect();
             PreparedStatement statement = connection.prepareStatement(sql)) {
            ResultSet rs = statement.executeQuery();
            
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "Không tìm thấy sinh viên có mã " + txtMaSV.getText(), "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Đã tìm thấy sinh viên, tiếp tục tải dữ liệu vào bảng
                loadTable.loadData(sql, jtbTK);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            // Xử lý các lỗi kết nối hoặc truy vấn
        }
    }
        
    }//GEN-LAST:event_btnTKActionPerformed

    private void txtMaSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaSVMouseClicked
        txtMaSV.setText("");
    }//GEN-LAST:event_txtMaSVMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfmTimKiemDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfmTimKiemDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfmTimKiemDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfmTimKiemDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfmTimKiemDiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbTK;
    private javax.swing.JTextField txtMaSV;
    // End of variables declaration//GEN-END:variables
    private void setIconImage() {
    
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/iconMain.jpg")));
   
}
}
